// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/port/pb.proto

package port

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on SavePortRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SavePortRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPort() == nil {
		return SavePortRequestValidationError{
			field:  "Port",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPort()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SavePortRequestValidationError{
				field:  "Port",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// SavePortRequestValidationError is the validation error returned by
// SavePortRequest.Validate if the designated constraints aren't met.
type SavePortRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortRequestValidationError) ErrorName() string { return "SavePortRequestValidationError" }

// Error satisfies the builtin error interface
func (e SavePortRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortRequestValidationError{}

// Validate checks the field values on SavePortResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SavePortResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// SavePortResponseValidationError is the validation error returned by
// SavePortResponse.Validate if the designated constraints aren't met.
type SavePortResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortResponseValidationError) ErrorName() string { return "SavePortResponseValidationError" }

// Error satisfies the builtin error interface
func (e SavePortResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortResponseValidationError{}

// Validate checks the field values on SavePortsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SavePortsRequest) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SavePortsRequestValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// SavePortsRequestValidationError is the validation error returned by
// SavePortsRequest.Validate if the designated constraints aren't met.
type SavePortsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortsRequestValidationError) ErrorName() string { return "SavePortsRequestValidationError" }

// Error satisfies the builtin error interface
func (e SavePortsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortsRequestValidationError{}

// Validate checks the field values on SavePortsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SavePortsResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// SavePortsResponseValidationError is the validation error returned by
// SavePortsResponse.Validate if the designated constraints aren't met.
type SavePortsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortsResponseValidationError) ErrorName() string {
	return "SavePortsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SavePortsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortsResponseValidationError{}

// Validate checks the field values on GetAllPortsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetAllPortsRequest) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetAllPortsRequestValidationError is the validation error returned by
// GetAllPortsRequest.Validate if the designated constraints aren't met.
type GetAllPortsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllPortsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllPortsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllPortsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllPortsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllPortsRequestValidationError) ErrorName() string {
	return "GetAllPortsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllPortsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllPortsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllPortsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllPortsRequestValidationError{}

// Validate checks the field values on GetAllPortsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetAllPortsResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAllPortsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// GetAllPortsResponseValidationError is the validation error returned by
// GetAllPortsResponse.Validate if the designated constraints aren't met.
type GetAllPortsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllPortsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllPortsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllPortsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllPortsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllPortsResponseValidationError) ErrorName() string {
	return "GetAllPortsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllPortsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllPortsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllPortsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllPortsResponseValidationError{}

// Validate checks the field values on PortEntity with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *PortEntity) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetID()) < 1 {
		return PortEntityValidationError{
			field:  "ID",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		return PortEntityValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetCity()) < 1 {
		return PortEntityValidationError{
			field:  "City",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for Province

	if utf8.RuneCountInString(m.GetCountry()) < 1 {
		return PortEntityValidationError{
			field:  "Country",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for Timezone

	// no validation rules for Code

	return nil
}

// PortEntityValidationError is the validation error returned by
// PortEntity.Validate if the designated constraints aren't met.
type PortEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PortEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PortEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PortEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PortEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PortEntityValidationError) ErrorName() string { return "PortEntityValidationError" }

// Error satisfies the builtin error interface
func (e PortEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPortEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PortEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PortEntityValidationError{}
