// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/port/pb.proto

package port

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// Service error codes
//
type PortServiceErrorCode int32

const (
	PortServiceErrorCode_Unknown        PortServiceErrorCode = 0
	PortServiceErrorCode_Internal       PortServiceErrorCode = 5000
	PortServiceErrorCode_InvalidRequest PortServiceErrorCode = 4000
)

var PortServiceErrorCode_name = map[int32]string{
	0:    "Unknown",
	5000: "Internal",
	4000: "InvalidRequest",
}

var PortServiceErrorCode_value = map[string]int32{
	"Unknown":        0,
	"Internal":       5000,
	"InvalidRequest": 4000,
}

func (x PortServiceErrorCode) String() string {
	return proto.EnumName(PortServiceErrorCode_name, int32(x))
}

func (PortServiceErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{0}
}

type SavePortRequest struct {
	Port                 *PortEntity `protobuf:"bytes,1,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SavePortRequest) Reset()         { *m = SavePortRequest{} }
func (m *SavePortRequest) String() string { return proto.CompactTextString(m) }
func (*SavePortRequest) ProtoMessage()    {}
func (*SavePortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{0}
}

func (m *SavePortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePortRequest.Unmarshal(m, b)
}
func (m *SavePortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePortRequest.Marshal(b, m, deterministic)
}
func (m *SavePortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePortRequest.Merge(m, src)
}
func (m *SavePortRequest) XXX_Size() int {
	return xxx_messageInfo_SavePortRequest.Size(m)
}
func (m *SavePortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavePortRequest proto.InternalMessageInfo

func (m *SavePortRequest) GetPort() *PortEntity {
	if m != nil {
		return m.Port
	}
	return nil
}

type SavePortResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavePortResponse) Reset()         { *m = SavePortResponse{} }
func (m *SavePortResponse) String() string { return proto.CompactTextString(m) }
func (*SavePortResponse) ProtoMessage()    {}
func (*SavePortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{1}
}

func (m *SavePortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePortResponse.Unmarshal(m, b)
}
func (m *SavePortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePortResponse.Marshal(b, m, deterministic)
}
func (m *SavePortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePortResponse.Merge(m, src)
}
func (m *SavePortResponse) XXX_Size() int {
	return xxx_messageInfo_SavePortResponse.Size(m)
}
func (m *SavePortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SavePortResponse proto.InternalMessageInfo

type SavePortsRequest struct {
	Items                []*PortEntity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SavePortsRequest) Reset()         { *m = SavePortsRequest{} }
func (m *SavePortsRequest) String() string { return proto.CompactTextString(m) }
func (*SavePortsRequest) ProtoMessage()    {}
func (*SavePortsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{2}
}

func (m *SavePortsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePortsRequest.Unmarshal(m, b)
}
func (m *SavePortsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePortsRequest.Marshal(b, m, deterministic)
}
func (m *SavePortsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePortsRequest.Merge(m, src)
}
func (m *SavePortsRequest) XXX_Size() int {
	return xxx_messageInfo_SavePortsRequest.Size(m)
}
func (m *SavePortsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePortsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavePortsRequest proto.InternalMessageInfo

func (m *SavePortsRequest) GetItems() []*PortEntity {
	if m != nil {
		return m.Items
	}
	return nil
}

type SavePortsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavePortsResponse) Reset()         { *m = SavePortsResponse{} }
func (m *SavePortsResponse) String() string { return proto.CompactTextString(m) }
func (*SavePortsResponse) ProtoMessage()    {}
func (*SavePortsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{3}
}

func (m *SavePortsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePortsResponse.Unmarshal(m, b)
}
func (m *SavePortsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePortsResponse.Marshal(b, m, deterministic)
}
func (m *SavePortsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePortsResponse.Merge(m, src)
}
func (m *SavePortsResponse) XXX_Size() int {
	return xxx_messageInfo_SavePortsResponse.Size(m)
}
func (m *SavePortsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePortsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SavePortsResponse proto.InternalMessageInfo

type GetAllPortsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPortsRequest) Reset()         { *m = GetAllPortsRequest{} }
func (m *GetAllPortsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPortsRequest) ProtoMessage()    {}
func (*GetAllPortsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{4}
}

func (m *GetAllPortsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPortsRequest.Unmarshal(m, b)
}
func (m *GetAllPortsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPortsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPortsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPortsRequest.Merge(m, src)
}
func (m *GetAllPortsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPortsRequest.Size(m)
}
func (m *GetAllPortsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPortsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPortsRequest proto.InternalMessageInfo

type GetAllPortsResponse struct {
	Items                []*PortEntity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAllPortsResponse) Reset()         { *m = GetAllPortsResponse{} }
func (m *GetAllPortsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPortsResponse) ProtoMessage()    {}
func (*GetAllPortsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{5}
}

func (m *GetAllPortsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPortsResponse.Unmarshal(m, b)
}
func (m *GetAllPortsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPortsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPortsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPortsResponse.Merge(m, src)
}
func (m *GetAllPortsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPortsResponse.Size(m)
}
func (m *GetAllPortsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPortsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPortsResponse proto.InternalMessageInfo

func (m *GetAllPortsResponse) GetItems() []*PortEntity {
	if m != nil {
		return m.Items
	}
	return nil
}

//
// Service entity
//
type PortEntity struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Coordinates          []float32 `protobuf:"fixed32,3,rep,packed,name=Coordinates,proto3" json:"Coordinates,omitempty"`
	City                 string    `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Province             string    `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`
	Country              string    `protobuf:"bytes,6,opt,name=Country,proto3" json:"Country,omitempty"`
	Alias                []string  `protobuf:"bytes,7,rep,name=Alias,proto3" json:"Alias,omitempty"`
	Regions              []string  `protobuf:"bytes,8,rep,name=Regions,proto3" json:"Regions,omitempty"`
	Timezone             string    `protobuf:"bytes,9,opt,name=Timezone,proto3" json:"Timezone,omitempty"`
	Unlocs               []string  `protobuf:"bytes,10,rep,name=Unlocs,proto3" json:"Unlocs,omitempty"`
	Code                 string    `protobuf:"bytes,11,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PortEntity) Reset()         { *m = PortEntity{} }
func (m *PortEntity) String() string { return proto.CompactTextString(m) }
func (*PortEntity) ProtoMessage()    {}
func (*PortEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_88004274c8d0ae2b, []int{6}
}

func (m *PortEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortEntity.Unmarshal(m, b)
}
func (m *PortEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortEntity.Marshal(b, m, deterministic)
}
func (m *PortEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortEntity.Merge(m, src)
}
func (m *PortEntity) XXX_Size() int {
	return xxx_messageInfo_PortEntity.Size(m)
}
func (m *PortEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_PortEntity.DiscardUnknown(m)
}

var xxx_messageInfo_PortEntity proto.InternalMessageInfo

func (m *PortEntity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PortEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PortEntity) GetCoordinates() []float32 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *PortEntity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PortEntity) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *PortEntity) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *PortEntity) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *PortEntity) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *PortEntity) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PortEntity) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *PortEntity) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterEnum("port.PortServiceErrorCode", PortServiceErrorCode_name, PortServiceErrorCode_value)
	proto.RegisterType((*SavePortRequest)(nil), "port.SavePortRequest")
	proto.RegisterType((*SavePortResponse)(nil), "port.SavePortResponse")
	proto.RegisterType((*SavePortsRequest)(nil), "port.SavePortsRequest")
	proto.RegisterType((*SavePortsResponse)(nil), "port.SavePortsResponse")
	proto.RegisterType((*GetAllPortsRequest)(nil), "port.GetAllPortsRequest")
	proto.RegisterType((*GetAllPortsResponse)(nil), "port.GetAllPortsResponse")
	proto.RegisterType((*PortEntity)(nil), "port.PortEntity")
}

func init() { proto.RegisterFile("pb/port/pb.proto", fileDescriptor_88004274c8d0ae2b) }

var fileDescriptor_88004274c8d0ae2b = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0x1f, 0x79, 0xf8, 0x5a, 0x80, 0xb9, 0x0d, 0xed, 0xd4, 0x12, 0xc2, 0x32, 0x12, 0x44,
	0x2c, 0x12, 0x54, 0x76, 0x20, 0x90, 0x1a, 0xa7, 0xaa, 0xbc, 0x41, 0x95, 0x4b, 0x37, 0xec, 0x9c,
	0x64, 0x84, 0x2c, 0x9c, 0x19, 0x33, 0x9e, 0x06, 0x85, 0x2f, 0x40, 0x7c, 0x05, 0xdf, 0xc1, 0xaa,
	0x9f, 0xc0, 0x6f, 0xf0, 0x17, 0x68, 0xc6, 0x71, 0x62, 0x9c, 0x2e, 0xd8, 0xcd, 0x39, 0xf7, 0xdc,
	0x73, 0x75, 0x67, 0xce, 0x80, 0x57, 0xcc, 0xc6, 0x05, 0x17, 0x72, 0x5c, 0xcc, 0x46, 0x85, 0xe0,
	0x92, 0xa3, 0xad, 0xa0, 0x7f, 0xbc, 0x4a, 0xf3, 0x6c, 0x91, 0x4a, 0x3a, 0xae, 0x0f, 0x55, 0x39,
	0x8c, 0xe0, 0xc1, 0x55, 0xba, 0xa2, 0x97, 0x5c, 0xc8, 0x84, 0x7e, 0xb9, 0xa1, 0xa5, 0xc4, 0x97,
	0x60, 0x2b, 0x48, 0x8c, 0xc0, 0x18, 0xba, 0xa7, 0xde, 0x48, 0x19, 0x8c, 0x14, 0x73, 0xce, 0x64,
	0x26, 0xd7, 0x13, 0xf8, 0xf5, 0xe7, 0xd6, 0xea, 0xfc, 0x30, 0x4c, 0xcf, 0x48, 0xb4, 0x32, 0x44,
	0xf0, 0x76, 0x26, 0x65, 0xc1, 0x59, 0x49, 0xc3, 0xd7, 0x3b, 0xae, 0xac, 0x9d, 0x9f, 0x41, 0x27,
	0x96, 0x74, 0x59, 0x12, 0x23, 0xb0, 0xee, 0xb2, 0x4e, 0xaa, 0x72, 0x78, 0x08, 0x0f, 0x1b, 0xbd,
	0x1b, 0xc3, 0x01, 0xe0, 0x05, 0x95, 0x67, 0x79, 0xde, 0xb4, 0x0c, 0xdf, 0xc2, 0xe1, 0x3f, 0x6c,
	0x25, 0xfe, 0xef, 0x49, 0xb7, 0x26, 0xc0, 0x8e, 0xc5, 0x13, 0x30, 0xe3, 0xa9, 0x5e, 0xdc, 0x99,
	0x38, 0x6a, 0x4d, 0x5b, 0xa8, 0x2d, 0xcd, 0x78, 0x8a, 0x8f, 0xc1, 0x7e, 0x9f, 0x2e, 0x29, 0x31,
	0xdb, 0x45, 0x4d, 0x63, 0x00, 0x6e, 0xc4, 0xb9, 0x58, 0x64, 0x2c, 0x95, 0xb4, 0x24, 0x56, 0x60,
	0x0d, 0xcd, 0xa4, 0x49, 0x29, 0x83, 0x28, 0x93, 0x6b, 0x62, 0xef, 0x19, 0x28, 0x1a, 0x7d, 0xe8,
	0x5f, 0x0a, 0xbe, 0xca, 0xd8, 0x9c, 0x92, 0x8e, 0x92, 0x24, 0x5b, 0x8c, 0x4f, 0xa1, 0x17, 0xf1,
	0x1b, 0x26, 0xc5, 0x9a, 0x74, 0xdb, 0xdd, 0x75, 0x05, 0x07, 0xd0, 0x39, 0xcb, 0xb3, 0xb4, 0x24,
	0xbd, 0xc0, 0x1a, 0x3a, 0x49, 0x05, 0x90, 0x40, 0x2f, 0xa1, 0x9f, 0x32, 0xce, 0x4a, 0xd2, 0xd7,
	0x7c, 0x0d, 0xd5, 0xc0, 0x0f, 0xd9, 0x92, 0x7e, 0xe3, 0x8c, 0x12, 0xa7, 0x1a, 0x58, 0x63, 0x3c,
	0x82, 0xee, 0x35, 0xcb, 0xf9, 0xbc, 0x24, 0xa0, 0x9b, 0x36, 0x08, 0x11, 0xec, 0x88, 0x2f, 0x28,
	0x71, 0xb5, 0x5e, 0x9f, 0x5f, 0x5c, 0xc0, 0x40, 0xdd, 0xe0, 0x15, 0x15, 0xab, 0x6c, 0x4e, 0xcf,
	0x85, 0xe0, 0x42, 0xf1, 0xe8, 0x42, 0xef, 0x9a, 0x7d, 0x66, 0xfc, 0x2b, 0xf3, 0x0e, 0xf0, 0x1e,
	0xf4, 0x63, 0x26, 0xa9, 0x60, 0x69, 0xee, 0x7d, 0x7f, 0x8e, 0x87, 0x70, 0x3f, 0x66, 0x3a, 0x89,
	0x9b, 0x77, 0xf4, 0x7e, 0x3e, 0x39, 0xfd, 0x6d, 0x80, 0xdb, 0x70, 0xc2, 0x37, 0xd0, 0xaf, 0x53,
	0x80, 0x8f, 0xaa, 0x07, 0x6c, 0x45, 0xd5, 0x3f, 0x6a, 0xd3, 0x9b, 0xac, 0x1c, 0xe0, 0x3b, 0x70,
	0xb6, 0x11, 0xc2, 0x96, 0xac, 0x0e, 0x8f, 0x7f, 0xbc, 0xc7, 0x6f, 0xfb, 0xa7, 0xe0, 0x36, 0x72,
	0x85, 0xa4, 0x52, 0xee, 0x07, 0xd0, 0x3f, 0xb9, 0xa3, 0x52, 0xbb, 0x4c, 0xba, 0x1f, 0xf5, 0xf7,
	0x9b, 0x75, 0xf5, 0x67, 0x7b, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x84, 0x62, 0x51, 0xb4, 0x9f,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress error if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	SavePort(ctx context.Context, in *SavePortRequest, opts ...grpc.CallOption) (*SavePortResponse, error)
	SavePorts(ctx context.Context, in *SavePortsRequest, opts ...grpc.CallOption) (*SavePortsResponse, error)
	GetAllPorts(ctx context.Context, in *GetAllPortsRequest, opts ...grpc.CallOption) (*GetAllPortsResponse, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) SavePort(ctx context.Context, in *SavePortRequest, opts ...grpc.CallOption) (*SavePortResponse, error) {
	out := new(SavePortResponse)
	err := c.cc.Invoke(ctx, "/port.PortService/SavePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) SavePorts(ctx context.Context, in *SavePortsRequest, opts ...grpc.CallOption) (*SavePortsResponse, error) {
	out := new(SavePortsResponse)
	err := c.cc.Invoke(ctx, "/port.PortService/SavePorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) GetAllPorts(ctx context.Context, in *GetAllPortsRequest, opts ...grpc.CallOption) (*GetAllPortsResponse, error) {
	out := new(GetAllPortsResponse)
	err := c.cc.Invoke(ctx, "/port.PortService/GetAllPorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	SavePort(context.Context, *SavePortRequest) (*SavePortResponse, error)
	SavePorts(context.Context, *SavePortsRequest) (*SavePortsResponse, error)
	GetAllPorts(context.Context, *GetAllPortsRequest) (*GetAllPortsResponse, error)
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_SavePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).SavePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/port.PortService/SavePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).SavePort(ctx, req.(*SavePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_SavePorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).SavePorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/port.PortService/SavePorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).SavePorts(ctx, req.(*SavePortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_GetAllPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).GetAllPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/port.PortService/GetAllPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).GetAllPorts(ctx, req.(*GetAllPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "port.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePort",
			Handler:    _PortService_SavePort_Handler,
		},
		{
			MethodName: "SavePorts",
			Handler:    _PortService_SavePorts_Handler,
		},
		{
			MethodName: "GetAllPorts",
			Handler:    _PortService_GetAllPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/port/pb.proto",
}
